# Area
- name: 'area: analytics'
  description: 'Area: Analytics'
  color: '#f4db01'
- name: 'area: ci'
  description: 'Area: The continuous integration setup'
  color: '#f4db01'
- name: 'area: docs'
  description: "Area: Documentation that isn't part of any crate such as README.md"
  color: '#f4db01'

# Type
- name: 'type: bug'
  description: 'Type: This is a bug.'
  color: '#f2edfc'
- name: 'type: enhancement'
  description: 'Type: A PR with an enhancement or bugfix.'
  color: '#f2edfc'
- name: 'type: maintenance'
  description: 'Type: PRs that clean code up or issues documenting cleanup.'
  color: '#f2edfc'
