# Area
- name: 'area: apps-web'
  description: ''
  color: '#f4db01'
- name: 'area: apps-admin'
  description: ''
  color: '#f4db01'
- name: 'area: apps-storybook'
  description: ''
  color: '#f4db01'
- name: 'area: packages-api'
  description: ''
  color: '#f4db01'
- name: 'area: packages-auth'
  description: ''
  color: '#f4db01'
- name: 'area: packages-db'
  description: ''
  color: '#f4db01'
- name: 'area: packages-google-apps-script'
  description: ''
  color: '#f4db01'
- name: 'area: packages-ui'
  description: ''
  color: '#f4db01'
- name: 'area: tooling-eslint'
  description: ''
  color: '#f4db01'
- name: 'area: tooling-prettier'
  description: ''
  color: '#f4db01'
- name: 'area: tooling-storybook'
  description: ''
  color: '#f4db01'
- name: 'area: tooling-tailwind'
  description: ''
  color: '#f4db01'
- name: 'area: tooling-typescript'
  description: ''
  color: '#f4db01'
- name: 'area: root'
  description: ''
  color: '#f4db01'

# Type
- name: 'type: bug'
  description: ''
  color: '#f2edfc'
- name: 'type: enhancement'
  description: ''
  color: '#f2edfc'
- name: 'type: cosmetics'
  description: ''
  color: '#f2edfc'
- name: 'type: exception'
  description: ''
  color: '#f2edfc'
- name: 'type: task'
  description: ''
  color: '#f2edfc'
- name: 'type: usability-problem'
  description: ''
  color: '#f2edfc'
- name: 'type: performance-problem'
  description: ''
  color: '#f2edfc'
- name: 'type: epic'
  description: ''
  color: '#f2edfc'
- name: 'type: bump-version'
  description: ''
  color: '#f2edfc'

# Priority
- name: 'priority: show-stopper'
  description: ''
  color: '#f4ab01'
- name: 'priority: critical'
  description: ''
  color: '#f4ab01'
- name: 'priority: major'
  description: ''
  color: '#f4ab01'
- name: 'priority: normal'
  description: ''
  color: '#f4ab01'
- name: 'priority: minor'
  description: ''
  color: '#f4ab01'

# Size
- name: 'size: x-large'
  description: ''
  color: '#d6bcf0'
- name: 'size: large'
  description: ''
  color: '#d6bcf0'
- name: 'size: medium'
  description: ''
  color: '#d6bcf0'
- name: 'size: small'
  description: ''
  color: '#d6bcf0'
- name: 'size: tiny'
  description: ''
  color: '#d6bcf0'

# Deploy
- name: 'deploy: develop'
  description: ''
  color: '#cfd9d9'
- name: 'deploy: staging'
  description: ''
  color: '#cfd9d9'
- name: 'deploy: production'
  description: ''
  color: '#cfd9d9'
