# Area
- name: A-analytics
  description: 'Area: Analytics'
  color: '#f4db01'
- name: A-ci
  description: 'Area: The continuous integration setup'
  color: '#f4db01'
- name: A-readme
  description: 'Area: Documentation that isn't part of any crate such as README.md'
  color: '#f4db01'

# Category
- name: C-bug
  description: 'Category: This is a bug.'
  color: '#f2edfc'
- name: C-enhancement
  description: 'Category: A PR with an enhancement or bugfix.'
  color: '#f2edfc'
- name: C-maintenance
  description: 'Category: PRs that clean code up or issues documenting cleanup.'
  color: '#f2edfc'
- name: C-maintenance
  description: 'Category: PRs that clean code up or issues documenting cleanup.'
  color: '#f2edfc'
