import type { CollectionEntry } from "astro:content";

export const mockMemos: CollectionEntry<"memo">[] = [
  {
    id: "memo-1.md",
    body: "This is memo 1",
    collection: "memo",
    data: {
      id: "memo-1",
      isDraft: false,
      createdAt: new Date("2025-01-01T00:00:00Z"),
      author: "kkhys",
      hideLinkCard: false,
      isBot: false,
      isPinned: false,
      hideComments: true,
      tag: "tech",
    },
  },
  {
    id: "memo-2.md",
    body: "This is memo 2",
    collection: "memo",
    data: {
      id: "memo-2",
      isDraft: false,
      createdAt: new Date("2025-11-20T00:00:00Z"),
      author: "kkhys",
      hideLinkCard: false,
      isBot: false,
      isPinned: false,
      hideComments: false,
      tag: "life",
    },
  },
  {
    id: "memo-3.md",
    body: "This is memo 3",
    collection: "memo",
    data: {
      id: "memo-3",
      isDraft: true,
      createdAt: new Date("2025-11-22T00:00:00Z"),
      author: "kkhys",
      hideLinkCard: false,
      isBot: false,
      isPinned: false,
      hideComments: false,
      tag: "tech",
    },
  },
  {
    id: "memo-4.md",
    body: "This is memo 4",
    collection: "memo",
    data: {
      id: "memo-4",
      isDraft: false,
      createdAt: new Date("2025-11-24T00:00:00Z"),
      author: "kkhys",
      hideLinkCard: false,
      isBot: false,
      isPinned: true,
      hideComments: false,
      tag: "work",
    },
  },
  {
    id: "memo-5.md",
    body: "",
    collection: "memo",
    data: {
      id: "memo-5",
      isDraft: false,
      createdAt: new Date("2025-11-25T00:00:00Z"),
      author: "kkhys",
      hideLinkCard: false,
      isBot: false,
      isPinned: false,
      hideComments: false,
    },
  },
  {
    id: "comment-1.md",
    body: "This is a comment on memo-1",
    collection: "memo",
    data: {
      id: "comment-1",
      isDraft: false,
      createdAt: new Date("2025-01-02T00:00:00Z"),
      author: "kkhys",
      hideLinkCard: false,
      isBot: false,
      isPinned: false,
      hideComments: false,
      comment: "memo-1",
    },
  },
  {
    id: "comment-2.md",
    body: "This is another comment on memo-1",
    collection: "memo",
    data: {
      id: "comment-2",
      isDraft: false,
      createdAt: new Date("2025-01-03T00:00:00Z"),
      author: "kkhys",
      hideLinkCard: false,
      isBot: false,
      isPinned: false,
      hideComments: false,
      comment: "memo-1",
    },
  },
  {
    id: "comment-3.md",
    body: "This is a comment on memo-2",
    collection: "memo",
    data: {
      id: "comment-3",
      isDraft: false,
      createdAt: new Date("2025-11-21T00:00:00Z"),
      author: "kkhys",
      hideLinkCard: false,
      isBot: false,
      isPinned: false,
      hideComments: false,
      comment: "memo-2",
    },
  },
  {
    id: "comment-4.md",
    body: "This is a draft comment on memo-1",
    collection: "memo",
    data: {
      id: "comment-4",
      isDraft: true,
      createdAt: new Date("2025-01-04T00:00:00Z"),
      author: "kkhys",
      hideLinkCard: false,
      isBot: false,
      isPinned: false,
      hideComments: false,
      comment: "memo-1",
    },
  },
  {
    id: "memo-6.md",
    body: "This is memo 6 by another user",
    collection: "memo",
    data: {
      id: "memo-6",
      isDraft: false,
      createdAt: new Date("2025-12-01T00:00:00Z"),
      author: "testuser",
      hideLinkCard: false,
      isBot: false,
      isPinned: false,
      hideComments: false,
      tag: "tech",
    },
  },
  {
    id: "rss-b1akmxp",
    body: "ビデオ会議はなぜ疲れるのか\n\nhttps://kkhys.me/blog/posts/b1akmxp",
    collection: "memo",
    data: {
      id: "rss-b1akmxp",
      isDraft: false,
      createdAt: new Date("2026-03-09T00:00:00Z"),
      author: "blog-feed",
      hideLinkCard: false,
      isBot: true,
      isPinned: false,
      hideComments: false,
    },
  },
  {
    id: "oss-gh-labeler",
    body: "gh-labeler\n\nhttps://github.com/kkhys/gh-labeler",
    collection: "memo",
    data: {
      id: "oss-gh-labeler",
      isDraft: false,
      createdAt: new Date("2025-09-07T01:54:02Z"),
      author: "oss-project",
      hideLinkCard: false,
      isBot: true,
      isPinned: false,
      hideComments: false,
    },
  },
  {
    id: "quote-1.md",
    body: "This is a quote of memo-1",
    collection: "memo",
    data: {
      id: "quote-1",
      isDraft: false,
      createdAt: new Date("2025-12-10T00:00:00Z"),
      author: "kkhys",
      hideLinkCard: false,
      isBot: false,
      isPinned: false,
      hideComments: false,
      quote: "memo-1",
    },
  },
  {
    id: "quote-2.md",
    body: "This is a quote of comment-1",
    collection: "memo",
    data: {
      id: "quote-2",
      isDraft: false,
      createdAt: new Date("2025-12-15T00:00:00Z"),
      author: "kkhys",
      hideLinkCard: false,
      isBot: false,
      isPinned: false,
      hideComments: false,
      quote: "comment-1",
    },
  },
];
