minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - scrub-exif

packages:
  - apps/*
  - packages/*
  - apps/me/me-content

allowBuilds:
  esbuild: true
  lefthook: true
  sharp: true
  workerd: false
