export const SITE_OWNER_SLUG = "kkhys" as const;
export const SITE_AUTHOR_NAME = "Keisuke Hayashi" as const;
export const SITE_URL = "https://memo.kkhys.me" as const;
export const BLOG_RSS_FEED_URL = "https://kkhys.me/rss.xml" as const;
export const ZENN_RSS_FEED_URL = "https://zenn.dev/kkhys/feed" as const;
export const TITLE = "Memo" as const;
export const DESCRIPTION = "日々のつぶやき" as const;
export const PAGE_SIZE = 20 as const;
export const TWITTER_ACCOUNT_NAME = "@kkhys_" as const;
