// This file was automatically generated on 2025-01-07T12:52:21.079Z.
// Please do not remove or edit this file.

export const postMetadata = [
  {
    title: "二代目昇降デスクを作った",
    slug: "p1tnt9a",
    emoji: "🔩",
    category: "Build",
    tags: ["Desk"],
    status: "published",
  },
  {
    title: "さよなら、My 自作 PC",
    slug: "p1ppkfs",
    emoji: "🖥️",
    category: "Object",
    tags: [],
    status: "published",
  },
  {
    title: "Vultr + Arch Linux で Mastodon を構築する",
    slug: "p1ffkqq",
    emoji: "🦣",
    category: "Tech",
    tags: [],
    status: "published",
  },
  {
    title: "星野リゾート「界アンジン」でのんびり",
    slug: "p15p4yn",
    emoji: "⛵️",
    category: "Life",
    tags: [],
    status: "published",
  },
  {
    title: "Redis を使った PV カウントに切り替える",
    slug: "p1ydlf6",
    emoji: "🛢️",
    category: "Tech",
    tags: [],
    status: "published",
  },
  {
    title: "v1.10.0 リリースノート: お問い合わせ機能の追加",
    slug: "p143t9d",
    emoji: "🚀",
    category: "Tech",
    tags: ["Release"],
    status: "published",
  },
  {
    title: "技術書にぴったりな文鎮",
    slug: "p1qhr64",
    emoji: "📗",
    category: "Object",
    tags: [],
    status: "published",
  },
  {
    title: "v1.9.0 リリースノート: Medium 風の画像ズーム機能を追加",
    slug: "p1kqv7s",
    emoji: "🚀",
    category: "Tech",
    tags: ["Release"],
    status: "published",
  },
  {
    title: "Vercel ビルド時に Playwright をインストールする",
    slug: "p128uug",
    emoji: "🎭",
    category: "Tech",
    tags: [],
    status: "published",
  },
  {
    title: "Animations on the web に登録した",
    slug: "p1gvayx",
    emoji: "🧈",
    category: "Tech",
    tags: [],
    status: "published",
  },
  {
    title: "エストニア電子国民として",
    slug: "p1t6el8",
    emoji: "🇪🇪",
    category: "Life",
    tags: [],
    status: "published",
  },
  {
    title: "OWASP ASVS から考えるパスワード要件",
    slug: "p164vu8",
    emoji: "🔑",
    category: "Tech",
    tags: ["Security"],
    status: "published",
  },
  {
    title: "月の土地をもらった",
    slug: "p1n03k6",
    emoji: "🌜",
    category: "Life",
    tags: [],
    status: "published",
  },
  {
    title: "v1.8.0 リリースノート: グローバルナビゲーションの追加など",
    slug: "p1c8jpk",
    emoji: "🚀",
    category: "Tech",
    tags: ["Release"],
    status: "published",
  },
  {
    title: "Noto Emoji を SVG 化する API を作る",
    slug: "p15e6x7",
    emoji: "🔄",
    category: "Tech",
    tags: [],
    status: "published",
  },
  {
    title: "デスク構成スナップショット 2024",
    slug: "p1v6tlh",
    emoji: "🖥️",
    category: "Object",
    tags: ["Desk"],
    status: "published",
  },
  {
    title: "新しいカメラを買った",
    slug: "p1672pu",
    emoji: "📷",
    category: "Object",
    tags: [],
    status: "published",
  },
  {
    title: "Web API の開発時に最低限覚えておくべきこと",
    slug: "p1ua4wh",
    emoji: "🔌",
    category: "Tech",
    tags: [],
    status: "published",
  },
  {
    title: "Next.js では searchParams の扱いにご用心",
    slug: "p1srf75",
    emoji: "🔼",
    category: "Tech",
    tags: ["Next.js"],
    status: "published",
  },
  {
    title: "v1.7.0 リリースノート: PV カウント",
    slug: "p1v9jvx",
    emoji: "🚀",
    category: "Tech",
    tags: ["Release"],
    status: "published",
  },
  {
    title: "バリ島旅行記",
    slug: "p1v00e8",
    emoji: "🏝️",
    category: "Life",
    tags: ["Travel"],
    status: "published",
  },
  {
    title: "v1.6.0 リリースノート: MDX コンポーネントの強化",
    slug: "p1r60de",
    emoji: "🚀",
    category: "Tech",
    tags: ["Release"],
    status: "published",
  },
  {
    title: "人生初の陶芸",
    slug: "p1wcla5",
    emoji: "🏺",
    category: "Build",
    tags: ["Pottery"],
    status: "published",
  },
  {
    title: "Play Framework のコンパイルに TypeScript を組み込む",
    slug: "p16ceda",
    emoji: "🔨",
    category: "Tech",
    tags: ["Play Framework", "TypeScript"],
    status: "published",
  },
  {
    title: "v1.5.0 リリースノート: 回遊率とシェア率向上のための施策",
    slug: "p1g6z2d",
    emoji: "🚀",
    category: "Tech",
    tags: ["Release"],
    status: "published",
  },
  {
    title: "セイルチェアの肘掛けを交換した",
    slug: "p1vdu33",
    emoji: "💺",
    category: "Build",
    tags: ["Desk"],
    status: "published",
  },
  {
    title: "バレンタインデー 2024",
    slug: "p18vcqd",
    emoji: "🍫",
    category: "Life",
    tags: [],
    status: "published",
  },
  {
    title: "Mermaid を泳がせる",
    slug: "p1eemm6",
    emoji: "🧜‍♀️",
    category: "Tech",
    tags: [],
    status: "published",
  },
  {
    title: "フォントのこだわり",
    slug: "p1fw2ts",
    emoji: "🔠",
    category: "Tech",
    tags: [],
    status: "published",
  },
  {
    title: "スラッグのこだわり",
    slug: "p1y4nft",
    emoji: "🔗",
    category: "Tech",
    tags: [],
    status: "published",
  },
  {
    title: "v1.4.0 リリースノート: 脈絡もない機能追加",
    slug: "p1rklfz",
    emoji: "🚀",
    category: "Tech",
    tags: ["Release"],
    status: "published",
  },
  {
    title: "七転び八起き / 2",
    slug: "p1e0lpm",
    emoji: "🏃",
    category: "Life",
    tags: ["Memorial"],
    status: "published",
  },
];
