import type { RehypeMermaidOptions } from "rehype-mermaid";

export const rehypeMermaidOptions = {
  mermaidConfig: {
    theme: "base",
    fontFamily:
      'ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
    fontSize: 13,
    themeVariables: {
      /* @see: https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/themes/theme-dark.js */

      // background: '',
      primaryColor: "#b0b0b0",
      secondaryColor: "#545480",

      // tertiaryColor: '',
      primaryBorderColor: "#4c4c53",
      // secondaryBorderColor: '',
      // tertiaryBorderColor: '',
      primaryTextColor: "#f4f4f5",
      secondaryTextColor: "#f4f4f5",
      // tertiaryTextColor: '',
      lineColor: "#4c4c53",
      textColor: "#f4f4f5",

      mainBkg: "#27272a",
      // secondBkg: '',
      // mainContrastColor: '',
      // darkTextColor: '',
      // border1: '',
      // border2: '',
      // arrowheadColor: '',
      // fontFamily: '',
      fontSize: "13px",
      // labelBackground: '',
      // THEME_COLOR_LIMIT: 12,

      /* Flowchart variables */
      // nodeBkg: '',
      nodeBorder: "#4c4c53",
      clusterBkg: "#2e2d37",
      clusterBorder: "#6e6580",
      // defaultLinkColor: '',
      titleColor: "#d4b8ef",
      edgeLabelBackground: "#544c00",

      /* Sequence Diagram variables */
      actorBorder: "#4c4c53",
      actorBkg: "#27272a",
      actorTextColor: "#f4f4f5",
      // actorLineColor: '',
      signalColor: "#f4f4f5",
      signalTextColor: "#f4f4f5",
      labelBoxBkgColor: "#27272a",
      labelBoxBorderColor: "#4c4c53",
      labelTextColor: "#f4f4f5",
      loopTextColor: "#faf#f4d701afa",
      noteBorderColor: "#7b731a",
      noteBkgColor: "#484826",
      noteTextColor: "#f4d701",
      // activationBorderColor : '',
      // activationBkgColor : '',
      sequenceNumberColor: "#27272a",

      /* Git graph variables */
      git0: "#808080",
      git1: "#4c4c53",
      git2: "#545480",
      git3: "#867d80",
      git4: "#54806f",
      git5: "#75807d",
      git6: "#b0b0b0",
      git7: "#80547c",

      // gitInv0: '',
      // gitInv1: '',
      // gitInv2: '',
      // gitInv3: '',
      // gitInv4: '',
      // gitInv5: '',
      // gitInv6: '',
      // gitInv7: '',

      gitBranchLabel0: "#f4f4f5",
      gitBranchLabel1: "#f4f4f5",
      gitBranchLabel2: "#f4f4f5",
      gitBranchLabel3: "#f4f4f5",
      gitBranchLabel4: "#f4f4f5",
      gitBranchLabel5: "#f4f4f5",
      gitBranchLabel6: "#f4f4f5",
      gitBranchLabel7: "#f4f4f5",

      tagLabelColor: "#f4d701",
      tagLabelBackground: "#484826",
      tagLabelBorder: "#7b731a",
      tagLabelFontSize: "10px",
      commitLabelColor: "#f4f4f5",
      commitLabelBackground: "#62626a",
      commitLabelFontSize: "10px",

      /* State variables */
      transitionColor: "#4c4c53",
      // transitionLabelColor: '',
      stateLabelColor: "#f4f4f5",
      stateBkg: "#27272a",
      // labelBackgroundColor: '',
      // compositeBackground: '',
      // altBackground: '',
      // compositeTitleBackground: '',
      // compositeBorder: '',
      innerEndBackground: "#27272a",
      specialStateColor: "#4c4c53",

      // errorBkgColor: '',
      // errorTextColor: '',

      // fillType0: '',
      // fillType1: '',
      // fillType2: '',
      // fillType3: '',
      // fillType4: '',
      // fillType5: '',
      // fillType6: '',
      // fillType7: '',
    },
  },
} satisfies RehypeMermaidOptions;
